/*
 * freertos_tasks_c_additions.h
 *
 *  Created on: 2 апр. 2020 г.
 *      Author: 79029
 */

#ifndef THIRD_PARTY_FREERTOS_SOURCE_INCLUDE_FREERTOS_TASKS_C_ADDITIONS_H_
#define THIRD_PARTY_FREERTOS_SOURCE_INCLUDE_FREERTOS_TASKS_C_ADDITIONS_H_





#endif /* THIRD_PARTY_FREERTOS_SOURCE_INCLUDE_FREERTOS_TASKS_C_ADDITIONS_H_ */
